export const engineeringRecipes = [
  {
    itemName: 'Wyrdwood Spear',
    xp: '1,425',
    recipeID: 'Procedural_SpearT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Wyrdwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Iron Ingot',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 5,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Steel Hatchet',
    xp: '330',
    recipeID: 'Procedural_HatchetT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Starmetal Skinning Knife',
    xp: '900',
    recipeID: 'Procedural_SkinningKnifeT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Wyrdwood Bow',
    xp: '1,425',
    recipeID: 'Procedural_BowT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Wyrdwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: "Hunter's Longshot",
    xp: '576',
    recipeID: '2hMusket_HuntersLongshotT2',
    craftingFee: 25,
    recipeLevel: 25,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Timber',
    type2: 'Item',
    ingredient3: 'Coarse Leather',
    type3: 'Item',
    ingredient4: 'Silver Ingot',
    type4: 'Item',
    ingredient5: 'Fae Iron',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Ironwood Bow',
    xp: '3,100',
    recipeID: 'Procedural_BowT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Ironwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Treated Wood Spear',
    xp: '204',
    recipeID: 'Procedural_SpearT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Timber',
    type1: 'Category_Only',
    ingredient2: 'Iron Ingot',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 10,
    qty2: 5,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ironwood Fishing Pole',
    xp: '3,100',
    recipeID: 'Procedural_FishingPoleT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Ironwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: "Siren's Call",
    xp: '3,750',
    recipeID: '2hBow_SirensCallT4',
    craftingFee: 184,
    recipeLevel: 142,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Wyrdwood Planks',
    type1: 'Item',
    ingredient2: 'Silk',
    type2: 'Item',
    ingredient3: 'Layered Leather',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'QuillbarkT1',
    type5: 'Item',
    ingredient6: 'ScalecordT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'The Lookout',
    xp: '7,285',
    recipeID: '2hBow_TheLookoutT5',
    craftingFee: 449,
    recipeLevel: 197,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Glittering Ebony',
    type1: 'Item',
    ingredient2: 'Phoenixweave',
    type2: 'Item',
    ingredient3: 'Runic Leather',
    type3: 'Item',
    ingredient4: 'EnchantedBowStringT5',
    type4: 'Item',
    ingredient5: 'BarbvineT1',
    type5: 'Item',
    ingredient6: 'ScaleclothT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Laquered Wood Spear',
    xp: '540',
    recipeID: 'Procedural_SpearT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Lumber',
    type1: 'Category_Only',
    ingredient2: 'Iron Ingot',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 11,
    qty2: 5,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Orichalcum Hatchet',
    xp: '2,015',
    recipeID: 'Procedural_HatchetT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Musket of the Corrupted Guardian',
    xp: '1,440',
    recipeID: '2hMusket_MusketoftheCorruptedGuardianT3',
    craftingFee: 75,
    recipeLevel: 80,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Lumber',
    type2: 'Item',
    ingredient3: 'Rugged Leather',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Void Steel',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Ironwood Spear',
    xp: '3,100',
    recipeID: 'Procedural_SpearT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Ironwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Iron Ingot',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 5,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: "Flawless Grandmaster's Spear",
    xp: '7,285',
    recipeID: '2hSpear_FlawlessGrandmastersSpearT5',
    craftingFee: 449,
    recipeLevel: 186,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Glittering Ebony',
    type2: 'Item',
    ingredient3: 'Runic Leather',
    type3: 'Item',
    ingredient4: 'EmbossedWrappingT5',
    type4: 'Item',
    ingredient5: 'Cinnabar',
    type5: 'Item',
    ingredient6: 'Scarhide',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Obelisk Guard Musket',
    xp: '870',
    recipeID: '2hMusketCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sparkling Bone Dust',
    type4: 'Item',
    ingredient5: 'Vial of Ancient Mutagen',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Strong Proficiency Booster',
    xp: '225',
    recipeID: 'ProficiencyBoosterT4',
    craftingFee: 37,
    recipeLevel: 120,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Air Essence',
    type1: 'Item',
    ingredient2: 'Soul Essence',
    type2: 'Item',
    ingredient3: 'WaterT1',
    type3: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Steel Skinning Knife',
    xp: '330',
    recipeID: 'Procedural_SkinningKnifeT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Orichalcum Harvesting Sickle',
    xp: '2,015',
    recipeID: 'Procedural_SickleT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Orichalcum Mining Pickaxe',
    xp: '3,100',
    recipeID: 'Procedural_MiningPickT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Starmetal Arrow',
    xp: '525',
    recipeID: 'ArrowT4',
    craftingFee: 37,
    recipeLevel: 100,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Wyrdwood Planks',
    type2: 'Item',
    ingredient3: 'Feather',
    type3: 'Item',
    qty1: 2,
    qty2: 2,
    qty3: 3,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Starmetal Musket',
    xp: '1,425',
    recipeID: 'Procedural_MusketT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Lazarus Watcher Spear',
    xp: '4,805',
    recipeID: '2hSpearCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Steel Harvesting Sickle',
    xp: '330',
    recipeID: 'Procedural_SickleT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Starmetal Hatchet',
    xp: '900',
    recipeID: 'Procedural_HatchetT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Deepwatcher Bow',
    xp: '2,250',
    recipeID: '2hBowCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Wyrdwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Flint Skinning Knife',
    xp: '',
    recipeID: '1hSkinningKnifeT1',
    craftingFee: 0,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Flint',
    type1: 'Item',
    ingredient2: 'Green Wood',
    type2: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Iron Logging Axe',
    xp: '204',
    recipeID: 'Procedural_LoggingAxeT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Obelisk Guard Bow',
    xp: '870',
    recipeID: '2hBowCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Lumber',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    ingredient4: 'Sparkling Bone Dust',
    type4: 'Item',
    ingredient5: 'Vial of Ancient Mutagen',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Flint Harvesting Sickle',
    xp: '',
    recipeID: '1hSickleT1',
    craftingFee: 0,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Flint',
    type1: 'Item',
    ingredient2: 'Green Wood',
    type2: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Faeforged Musket',
    xp: '7,285',
    recipeID: '2hMusket_FaeforgedMusketT5',
    craftingFee: 449,
    recipeLevel: 195,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Glittering Ebony',
    type2: 'Item',
    ingredient3: 'Runic Leather',
    type3: 'Item',
    ingredient4: 'IntricateLockT5',
    type4: 'Item',
    ingredient5: 'TolviumT1',
    type5: 'Item',
    ingredient6: 'Scarhide',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Garden Keeper Hatchet',
    xp: '3,720',
    recipeID: '1hThrowingAxeCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'StickyVinesT1',
    type4: 'Item',
    ingredient5: 'PutridBarkT1',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: "Archmage's Assistant",
    xp: '2,625',
    recipeID: '1hThrowingAxe_ArchmagesAssistantT4',
    craftingFee: 184,
    recipeLevel: 143,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'BlessedCrucibleT1',
    type5: 'Item',
    ingredient6: 'BrightscaleHideT1',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Obelisk Guard Spear',
    xp: '870',
    recipeID: '2hSpearCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sparkling Bone Dust',
    type4: 'Item',
    ingredient5: 'Vial of Ancient Mutagen',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Dryad Walking Stick',
    xp: '576',
    recipeID: '2hSpear_DryadWalkingStickT2',
    craftingFee: 25,
    recipeLevel: 26,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Timber',
    type2: 'Item',
    ingredient3: 'Coarse Leather',
    type3: 'Item',
    ingredient4: 'Silver Ingot',
    type4: 'Item',
    ingredient5: 'Fae Iron',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Bow of the Dark Ranger',
    xp: '1,440',
    recipeID: '2hBow_BowoftheDarkRangerT3',
    craftingFee: 75,
    recipeLevel: 82,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Sateen',
    type2: 'Item',
    ingredient3: 'Rugged Leather',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'WhisperwoodT1',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Aged Wood Fishing Pole',
    xp: '540',
    recipeID: 'Procedural_FishingPoleT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Lumber',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Garden Keeper Bow',
    xp: '4,805',
    recipeID: '2hBowCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Ironwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    ingredient4: 'StickyVinesT1',
    type4: 'Item',
    ingredient5: 'PutridBarkT1',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Orichalcum Arrow',
    xp: '930',
    recipeID: 'ArrowT5',
    craftingFee: 90,
    recipeLevel: 150,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Item',
    ingredient2: 'Ironwood Planks',
    type2: 'Item',
    ingredient3: 'Feather',
    type3: 'Item',
    qty1: 1,
    qty2: 2,
    qty3: 3,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Corrupted Remnant',
    xp: '990',
    recipeID: '1hThrowingAxe_CorruptedRemnantT3',
    craftingFee: 75,
    recipeLevel: 78,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Void Steel',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Irreverent Edge',
    xp: '3,750',
    recipeID: '2hSpear_IrreverentEdgeT4',
    craftingFee: 184,
    recipeLevel: 146,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Wyrdwood Planks',
    type2: 'Item',
    ingredient3: 'Layered Leather',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'Azurite Chunk',
    type5: 'Item',
    ingredient6: 'BrightscaleHideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Deepwatcher Hatchet',
    xp: '1,725',
    recipeID: '1hThrowingAxeCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Last Light',
    xp: '1,440',
    recipeID: '2hSpear_LastLightT3',
    craftingFee: 75,
    recipeLevel: 76,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Lumber',
    type2: 'Item',
    ingredient3: 'Rugged Leather',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Void Steel',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Amrine Temple Bow',
    xp: '870',
    recipeID: '2hBowCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Lumber',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'MutagenLostT1',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Gunpowder',
    xp: '96',
    recipeID: 'GunpowderT2',
    craftingFee: 5,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Charcoal',
    type1: 'Item',
    ingredient2: 'Flint',
    type2: 'Item',
    ingredient3: 'Saltpeter',
    type3: 'Item',
    qty1: 5,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Wyrdwood Fishing Pole',
    xp: '1,425',
    recipeID: 'Procedural_FishingPoleT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Wyrdwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Obelisk Guard Hatchet',
    xp: '660',
    recipeID: '1hThrowingAxeCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sparkling Bone Dust',
    type4: 'Item',
    ingredient5: 'Vial of Ancient Mutagen',
    type5: 'Item',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Longbow of the Arcane Eye',
    xp: '3,750',
    recipeID: '2hBow_LongbowoftheArcaneEyeT4',
    craftingFee: 184,
    recipeLevel: 147,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Wyrdwood Planks',
    type1: 'Item',
    ingredient2: 'Silk',
    type2: 'Item',
    ingredient3: 'Layered Leather',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'EbonwoodT1',
    type5: 'Item',
    ingredient6: 'GlintwoolT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Steel Mining Pickaxe',
    xp: '540',
    recipeID: 'Procedural_MiningPickT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Amrine Temple Musket',
    xp: '870',
    recipeID: '2hMusketCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'MutagenLostT1',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Starmetal Logging Axe',
    xp: '1,425',
    recipeID: 'Procedural_LoggingAxeT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Treated Wood Bow',
    xp: '204',
    recipeID: 'Procedural_BowT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Timber',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Fear of Peace',
    xp: '7,285',
    recipeID: '2hMusket_FearOfPeaceT5',
    craftingFee: 449,
    recipeLevel: 190,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Glittering Ebony',
    type2: 'Item',
    ingredient3: 'Runic Leather',
    type3: 'Item',
    ingredient4: 'IntricateLockT5',
    type4: 'Item',
    ingredient5: 'Cinnabar',
    type5: 'Item',
    ingredient6: 'SmolderhideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Lazarus Watcher Hatchet',
    xp: '3,720',
    recipeID: '1hThrowingAxeCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Iron Mining Pickaxe',
    xp: '204',
    recipeID: 'Procedural_MiningPickT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Iron Harvesting Sickle',
    xp: '120',
    recipeID: 'Procedural_SickleT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 7,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Deepwatcher Musket',
    xp: '2,250',
    recipeID: '2hMusketCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Steel Arrow',
    xp: '240',
    recipeID: 'ArrowT3',
    craftingFee: 15,
    recipeLevel: 50,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Lumber',
    type2: 'Item',
    ingredient3: 'Feather',
    type3: 'Item',
    qty1: 3,
    qty2: 2,
    qty3: 3,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Thread of Fate',
    xp: '1,440',
    recipeID: '2hBow_ThreadOfFateT3',
    craftingFee: 75,
    recipeLevel: 77,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Sateen',
    type2: 'Item',
    ingredient3: 'Rugged Leather',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'WhisperwoodT1',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Treated Wood Fishing Pole',
    xp: '204',
    recipeID: 'Procedural_FishingPoleT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Timber',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Iron Hatchet',
    xp: '120',
    recipeID: 'Procedural_HatchetT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 7,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Orichalcum Musket',
    xp: '3,100',
    recipeID: 'Procedural_MusketT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Lacquered Wood Bow',
    xp: '540',
    recipeID: 'Procedural_BowT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Lumber',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Shipyard Sentinel Bow',
    xp: '2,250',
    recipeID: '2hBowCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Wyrdwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Shipyard Sentinel Musket',
    xp: '2,250',
    recipeID: '2hMusketCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Iron Arrow',
    xp: '108',
    recipeID: 'ArrowT2',
    craftingFee: 5,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Timber',
    type2: 'Item',
    ingredient3: 'Feather',
    type3: 'Item',
    qty1: 4,
    qty2: 2,
    qty3: 3,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Sandscribe',
    xp: '2,625',
    recipeID: '1hThrowingAxe_SandscribeT4',
    craftingFee: 184,
    recipeLevel: 148,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'Azurite Chunk',
    type5: 'Item',
    ingredient6: 'Scarhide',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Amrine Temple Spear',
    xp: '870',
    recipeID: '2hSpearCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'MutagenLostT1',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: "Sapling's Fury",
    xp: '396',
    recipeID: '1hThrowingAxe_SaplingsFuryT2',
    craftingFee: 25,
    recipeLevel: 28,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Coarse Leather',
    type2: 'Item',
    ingredient3: 'Timber',
    type3: 'Item',
    ingredient4: 'Silver Ingot',
    type4: 'Item',
    ingredient5: 'Fae Iron',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Longsight',
    xp: '7,285',
    recipeID: '2hBow_LongsightT5',
    craftingFee: 449,
    recipeLevel: 187,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Glittering Ebony',
    type1: 'Item',
    ingredient2: 'Phoenixweave',
    type2: 'Item',
    ingredient3: 'Runic Leather',
    type3: 'Item',
    ingredient4: 'EnchantedBowStringT5',
    type4: 'Item',
    ingredient5: 'WildwoodT1',
    type5: 'Item',
    ingredient6: 'BlisterweaveT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Iron Musket',
    xp: '204',
    recipeID: 'Procedural_MusketT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Lazarus Watcher Bow',
    xp: '4,805',
    recipeID: '2hBowCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Ironwood Planks',
    type1: 'Category_Only',
    ingredient2: 'Coarse Leather',
    type2: 'Category_Only',
    ingredient3: 'Linen',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Steel Cartridge',
    xp: '180',
    recipeID: 'ShotT3',
    craftingFee: 15,
    recipeLevel: 50,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Sateen',
    type2: 'Item',
    ingredient3: 'Gunpowder',
    type3: 'Item',
    qty1: 3,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Calamity',
    xp: '1,440',
    recipeID: '2hMusket_CalamityT3',
    craftingFee: 75,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Lumber',
    type2: 'Item',
    ingredient3: 'Rugged Leather',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Void Steel',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Starmetal Mining Pickaxe',
    xp: '1,425',
    recipeID: 'Procedural_MiningPickT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Shipyard Sentinel Spear',
    xp: '2,250',
    recipeID: '2hSpearCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Venerable Recurve',
    xp: '576',
    recipeID: '2hBow_VenerableRecurveT2',
    craftingFee: 25,
    recipeLevel: 27,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Linen',
    type2: 'Item',
    ingredient3: 'Coarse Leather',
    type3: 'Item',
    ingredient4: 'Silver Ingot',
    type4: 'Item',
    ingredient5: 'PetrifiedWoodT1',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Steel Logging Axe',
    xp: '540',
    recipeID: 'Procedural_LoggingAxeT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Common Proficiency Booster',
    xp: '90',
    recipeID: 'ProficiencyBoosterT3',
    craftingFee: 15,
    recipeLevel: 70,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Air Wisp',
    type1: 'Item',
    ingredient2: 'Soul Wisp',
    type2: 'Item',
    ingredient3: 'WaterT1',
    type3: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Weak Proficiency Booster',
    xp: '36',
    recipeID: 'ProficiencyBoosterT2',
    craftingFee: 5,
    recipeLevel: 20,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Air Mote',
    type1: 'Item',
    ingredient2: 'Soul Mote',
    type2: 'Item',
    ingredient3: 'WaterT1',
    type3: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Orichalcum Logging Axe',
    xp: '3,100',
    recipeID: 'Procedural_LoggingAxeT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: "Pixie's Punisher",
    xp: '4,960',
    recipeID: '1hThrowingAxe_PixiesPunisherT5',
    craftingFee: 449,
    recipeLevel: 198,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EmbossedWrappingT5',
    type4: 'Item',
    ingredient5: 'TolviumT1',
    type5: 'Item',
    ingredient6: 'TolviumT1',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Steel Musket',
    xp: '540',
    recipeID: 'Procedural_MusketT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Garden Keeper Musket',
    xp: '4,805',
    recipeID: '2hMusketCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'StickyVinesT1',
    type4: 'Item',
    ingredient5: 'PutridBarkT1',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Shipyard Sentinel Hatchet',
    xp: '1,725',
    recipeID: '1hThrowingAxeCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Manashot Blunderbuss',
    xp: '3,750',
    recipeID: '2hMusket_ManashotMusketT4',
    craftingFee: 184,
    recipeLevel: 140,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Wyrdwood Planks',
    type2: 'Item',
    ingredient3: 'Layered Leather',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'BlessedCrucibleT1',
    type5: 'Item',
    ingredient6: 'BrightscaleHideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Deepwatcher Spear',
    xp: '2,250',
    recipeID: '2hSpearCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Iron Skinning Knife',
    xp: '120',
    recipeID: 'Procedural_SkinningKnifeT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 7,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Orichalcum Cartridge',
    xp: '775',
    recipeID: 'ShotT5',
    craftingFee: 90,
    recipeLevel: 150,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Item',
    ingredient2: 'Infused Silk',
    type2: 'Item',
    ingredient3: 'Gunpowder',
    type3: 'Item',
    qty1: 1,
    qty2: 3,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Wooden Fishing Pole',
    xp: '',
    recipeID: '2hFishingPoleT1',
    craftingFee: 0,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Green Wood',
    type1: 'Item',
    ingredient2: 'FiberT1',
    type2: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Amrine Temple Hatchet',
    xp: '660',
    recipeID: '1hThrowingAxeCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'MutagenLostT1',
    type5: 'Item',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Garden Keeper Spear',
    xp: '4,805',
    recipeID: '2hSpearCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'StickyVinesT1',
    type4: 'Item',
    ingredient5: 'PutridBarkT1',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Flint Mining Pick',
    xp: '',
    recipeID: '1hPickT1',
    craftingFee: 0,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Flint',
    type1: 'Item',
    ingredient2: 'Green Wood',
    type2: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Starmetal Cartridge',
    xp: '375',
    recipeID: 'ShotT4',
    craftingFee: 37,
    recipeLevel: 100,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Silk',
    type2: 'Item',
    ingredient3: 'Gunpowder',
    type3: 'Item',
    qty1: 2,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Powerful Proficiency Booster',
    xp: '465',
    recipeID: 'ProficiencyBoosterT5',
    craftingFee: 90,
    recipeLevel: 170,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Air Quintessence',
    type1: 'Item',
    ingredient2: 'Soul Quintessence',
    type2: 'Item',
    ingredient3: 'AzothWatert1',
    type3: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: "Faedragon's Claw",
    xp: '7,285',
    recipeID: '2hSpear_FaedragonsClawT5',
    craftingFee: 449,
    recipeLevel: 196,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Glittering Ebony',
    type2: 'Item',
    ingredient3: 'Runic Leather',
    type3: 'Item',
    ingredient4: 'EmbossedWrappingT5',
    type4: 'Item',
    ingredient5: 'TolviumT1',
    type5: 'Item',
    ingredient6: 'SmolderhideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Orichalcum Skinning Knife',
    xp: '2,015',
    recipeID: 'Procedural_SkinningKnifeT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Flint Arrow',
    xp: '',
    recipeID: 'ArrowT1',
    craftingFee: 0,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Flint',
    type1: 'Item',
    ingredient2: 'Green Wood',
    type2: 'Item',
    ingredient3: 'Feather',
    type3: 'Item',
    qty1: 5,
    qty2: 2,
    qty3: 3,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Best Wishes',
    xp: '4,960',
    recipeID: '1hThrowingAxe_BestWishesT5',
    craftingFee: 449,
    recipeLevel: 193,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EmbossedWrappingT5',
    type4: 'Item',
    ingredient5: 'Cinnabar',
    type5: 'Item',
    ingredient6: 'SmolderhideT1',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: "Crow's Nest",
    xp: '990',
    recipeID: '1hThrowingAxe_CrowsNestT3',
    craftingFee: 75,
    recipeLevel: 83,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Void Steel',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Lazarus Watcher Musket',
    xp: '4,805',
    recipeID: '2hMusketCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Iron Cartridge',
    xp: '72',
    recipeID: 'ShotT2',
    craftingFee: 5,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Linen',
    type2: 'Item',
    ingredient3: 'Gunpowder',
    type3: 'Item',
    qty1: 4,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Bloodright',
    xp: '3,750',
    recipeID: '2hSpear_BloodrightT4',
    craftingFee: 184,
    recipeLevel: 136,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Wyrdwood Planks',
    type2: 'Item',
    ingredient3: 'Layered Leather',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'BlessedCrucibleT1',
    type5: 'Item',
    ingredient6: 'ShifthideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Spread of Malice',
    xp: '1,440',
    recipeID: '2hSpear_SpreadofMaliceT3',
    craftingFee: 75,
    recipeLevel: 81,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Lumber',
    type2: 'Item',
    ingredient3: 'Rugged Leather',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Void Steel',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Rifle of Sinister Deeds',
    xp: '3,750',
    recipeID: '2hMusket_RifleofSinisterDeedsT4',
    craftingFee: 184,
    recipeLevel: 145,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Wyrdwood Planks',
    type2: 'Item',
    ingredient3: 'Layered Leather',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'Azurite Chunk',
    type5: 'Item',
    ingredient6: 'ShifthideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Flint Logging Axe',
    xp: '',
    recipeID: '1hHatchetT1',
    craftingFee: 0,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Flint',
    type1: 'Item',
    ingredient2: 'Green Wood',
    type2: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Starmetal Harvesting Sickle',
    xp: '900',
    recipeID: 'Procedural_SickleT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
]
