export const furnishingRecipes = [
  {
    itemName: 'Ash Armoire',
    xp: '282',
    recipeID: 'House_HousingItem_Settler_Armoire01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash End Table',
    xp: '282',
    recipeID: 'House_HousingItem_Table_Settler_BedSideTable_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Cabinet',
    xp: '282',
    recipeID: 'House_HousingItem_Settler_Cabinet02_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Weak Incense',
    xp: '24',
    recipeID: 'IncenseT2',
    craftingFee: 5,
    recipeLevel: 20,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Hyssop',
    type2: 'Item',
    ingredient3: 'Cinnamon',
    type3: 'Item',
    ingredient4: 'Charcoal',
    type4: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 1,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Mahogany Stain',
    xp: '1,344',
    recipeID: 'WoodStainT5',
    craftingFee: 90,
    recipeLevel: 150,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Pure Solvent',
    type1: 'Item',
    ingredient2: 'Oil',
    type2: 'Item',
    qty1: 10,
    qty2: 4,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Ash Stain',
    xp: '14',
    recipeID: 'Ash Stain',
    craftingFee: 5,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Charcoal',
    type1: 'Item',
    ingredient2: 'Weak Solvent',
    type2: 'Item',
    qty1: 10,
    qty2: 4,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Minor Skinning Gathering Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Skinning_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Air Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Ash Wall Shelf',
    xp: '126',
    recipeID: 'House_HousingItem_Settler_Shelf01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Minor Mining Gathering Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Mining_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Earth Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Cerulean Curtains',
    xp: '138',
    recipeID: 'House_HousingItem_Settler_Decor_Wall_Curtain03_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Linen',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'PigmentBlue',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 3,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Minor Armoring Crafting Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Outfitting_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Fire Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Cerulean Valance',
    xp: '138',
    recipeID: 'House_HousingItem_Settler_Decor_Wall_Curtain02_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Linen',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'PigmentBlue',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 3,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Minor Logging Gathering Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Logging_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Air Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Strong Incense',
    xp: '384',
    recipeID: 'IncenseT4',
    craftingFee: 37,
    recipeLevel: 120,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Wyrdwood Planks',
    type1: 'Item',
    ingredient2: 'Hyssop',
    type2: 'Item',
    ingredient3: 'Cinnamon',
    type3: 'Item',
    ingredient4: 'Charcoal',
    type4: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 1,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Old Placesetting',
    xp: '96',
    recipeID: 'House_HousingItem_HW_Placesetting',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Weak Solvent',
    type3: 'Item',
    qty1: 10,
    qty2: 5,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Hewn Log Storage Chest',
    xp: '282',
    recipeID: 'House_HousingItem_Storage_T1_ChestOldLog',
    craftingFee: 18,
    recipeLevel: 35,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    ingredient4: 'HoldingRuneT2',
    type4: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 1,
    qty4: 1,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Round Sunny Rug',
    xp: '150',
    recipeID: 'House_HousingItem_Rug_Settler_Decor_Floor_Rug01',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Linen',
    type1: 'Item',
    ingredient2: 'Crossweave',
    type2: 'Item',
    ingredient3: 'Fiber',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 5,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Powerful Incense',
    xp: '1,280',
    recipeID: 'IncenseT5',
    craftingFee: 90,
    recipeLevel: 170,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Ironwood Planks',
    type1: 'Item',
    ingredient2: 'Hyssop',
    type2: 'Item',
    ingredient3: 'Cinnamon',
    type3: 'Item',
    ingredient4: 'Charcoal',
    type4: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 1,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Ash Dresser',
    xp: '282',
    recipeID: 'House_HousingItem_Settler_Dresser01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Minor Arcana Crafting Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Alchemy_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Earth Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Minor Cooking Crafting Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Cooking_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Water Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Warm Iron Lantern - Bright',
    xp: '150',
    recipeID: 'House_HousingItem_Lighting_Settler_LightTable01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Oil',
    type2: 'Item',
    ingredient3: 'Fiber',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 5,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Small Bookcase',
    xp: '282',
    recipeID: 'House_HousingItem_Settler_Bookcase01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Chest of Drawers',
    xp: '282',
    recipeID: 'House_HousingItem_Settler_Cabinet01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Warm Iron Chandelier - Bright',
    xp: '150',
    recipeID: 'House_HousingItem_Lighting_Settler_LightHanging01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Oil',
    type2: 'Item',
    ingredient3: 'Fiber',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 5,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Oak Stain',
    xp: '336',
    recipeID: 'Oak Stain',
    craftingFee: 37,
    recipeLevel: 100,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Potent Solvent',
    type1: 'Item',
    ingredient2: 'Oil',
    type2: 'Item',
    qty1: 10,
    qty2: 4,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Minor Harvesting Gathering Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Harvesting_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Water Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Minor Fishing Gathering Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Fishing_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Water Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Minor Ancients Combat Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Damage_Vs_Ancients_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Soul Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: "Iron Settler's Stove",
    xp: '282',
    recipeID: 'House_HousingItem_Settler_Stove01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Dining Chair',
    xp: '156',
    recipeID: 'House_HousingItem_Chair_Settler_Chair01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 15,
    qty2: 10,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Rusty Iron Lantern',
    xp: '150',
    recipeID: 'House_HousingItem_Lighting_Lantern_C',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Oil',
    type2: 'Item',
    ingredient3: 'Fiber',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 5,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Cerulean Sheets Bunk Bed',
    xp: '282',
    recipeID: 'House_HousingItem_Bed_Settler_Bed01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Minor Corrupted Combat Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Damage_Vs_Corrupted_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Life Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Cerulean Drape',
    xp: '138',
    recipeID: 'House_HousingItem_Settler_Decor_Wall_Curtain01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Linen',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'PigmentBlue',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 3,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Minor Lost Combat Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Damage_Vs_Lost_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Death Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Minor Engineering Crafting Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Engineering_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Air Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Warm Iron Sconce - Bright',
    xp: '150',
    recipeID: 'House_HousingItem_Lighting_Settler_LightWall01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Oil',
    type3: 'Item',
    qty1: 15,
    qty2: 5,
    qty3: 5,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Iron Storage Chest',
    xp: '1,128',
    recipeID: 'House_HousingItem_Storage_T2_ChestIron',
    craftingFee: 50,
    recipeLevel: 85,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'HoldingRuneT3',
    type4: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 1,
    qty4: 1,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Wicker Basket',
    xp: '61',
    recipeID: 'House_HousingItem_Basket_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'ReedT1',
    type1: 'Item',
    ingredient2: 'Fiber',
    type2: 'Item',
    ingredient3: 'Weak Solvent',
    type3: 'Item',
    qty1: 35,
    qty2: 25,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Desk',
    xp: '282',
    recipeID: 'House_HousingItem_Table_Settler_Desk01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Full Bed',
    xp: '282',
    recipeID: 'House_HousingItem_Bed_Settler_Bed02_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Minor Angry Earth Combat Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Damage_Vs_AngryEarth_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Earth Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Common Incense',
    xp: '96',
    recipeID: 'IncenseT3',
    craftingFee: 15,
    recipeLevel: 70,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Hyssop',
    type2: 'Item',
    ingredient3: 'Cinnamon',
    type3: 'Item',
    ingredient4: 'Charcoal',
    type4: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 1,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Ash Small Table',
    xp: '282',
    recipeID: 'House_HousingItem_Table_Settler_Table01_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Bar Stool',
    xp: '156',
    recipeID: 'House_HousingItem_Chair_Settler_Stool_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 15,
    qty2: 10,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Large Table',
    xp: '1,128',
    recipeID: 'House_HousingItem_Table_Settler_Table02_A',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Large Bookcase',
    xp: '282',
    recipeID: 'House_HousingItem_Settler_Bookcase02_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Minor Wildlife Combat Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Damage_Vs_Beasts_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Fire Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Minor Weaponsmithing Crafting Trophy',
    xp: '1,704',
    recipeID: 'House_HousingItem_Buff_Blacksmithing_Bonus_T1',
    craftingFee: 50,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    ingredient4: 'Fire Mote',
    type4: 'Item',
    qty1: 25,
    qty2: 20,
    qty3: 1,
    qty4: 25,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 4,
  },
  {
    itemName: 'Open Rickety Bookcase',
    xp: '282',
    recipeID: 'House_HousingItem_Alchemist_Cabinet_A',
    craftingFee: 18,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Timber',
    type1: 'Item',
    ingredient2: 'Iron Ingot',
    type2: 'Item',
    ingredient3: 'Ash Stain',
    type3: 'Item',
    qty1: 30,
    qty2: 15,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Ash Casual Chair',
    xp: '624',
    recipeID: 'House_HousingItem_Chair_Settler_Chair02_A',
    craftingFee: 50,
    recipeLevel: 50,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lumber',
    type1: 'Item',
    ingredient2: 'Steel Ingot',
    type2: 'Item',
    ingredient3: 'Maple Stain',
    type3: 'Item',
    qty1: 15,
    qty2: 10,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Maple Stain',
    xp: '84',
    recipeID: 'Maple Stain',
    craftingFee: 15,
    recipeLevel: 50,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Weak Solvent',
    type1: 'Item',
    ingredient2: 'Oil',
    type2: 'Item',
    qty1: 10,
    qty2: 4,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
]
