export const materialConversions = {
  Leather: { 'Raw Hide': 4 },
  'Coarse Leather': { 'Raw Hide': 4 },
  'Rugged Leather': { 'Raw Hide': 16, Tannin: 1 },
  'Layered Leather': { 'Thick Hide': 6, 'Raw Hide': 32, Tannin: 3 },
  'Infused Leather': {
    'Iron Hide': 8,
    'Thick Hide': 12,
    'Raw Hide': 64,
    Tannin: 7,
  },

  Metal: { 'Iron Ore': 4 },
  'Iron Ingot': { 'Iron Ore': 4 },
  'Steel Ingot': { 'Iron Ore': 12, 'Sand Flux': 1, Charcoal: 2 },
  'Starmetal Ingot': {
    'Iron Ore': 24,
    'Starmetal Ore': 6,
    'Sand Flux': 3,
    Charcoal: 12,
  },
  Charcoal: { 'Green Wood': 2 },

  'Orichalcum Ingot': {
    'Iron Ore': 48,
    'Orichalcum Ore': 8,
    'Starmetal Ore': 12,
    'Sand Flux': 7,
    Charcoal: 26,
  },
  'Silver Ingot': { 'Silver Ore': 4 },
  'Gold Ingot': { 'Silver Ore': 8, 'Gold Ore': 5, 'Sand Flux': 1 },
  'Platinum Ingot': {
    'Silver Ore': 16,
    'Gold Ore': 10,
    'Platinum Ore': 6,
    'Sand Flux': 3,
  },

  Cloth: { Fiber: 4 },
  Linen: { Fiber: 4 },
  Sateen: { Fiber: 16, Crossweave: 1 },
  Silk: { Fiber: 32, 'Silk Threads': 6, Crossweave: 2 },
  'Infused Silk': { Fiber: 64, 'Wire Fiber': 8, Crossweave: 3 },

  'Fire Wisp': { 'Fire Mote': 5 },
  'Earth Wisp': { 'Earth Mote': 5 },
  'Air Wisp': { 'Air Mote': 5 },
  'Water Wisp': { 'Water Mote': 5 },
  'Death Wisp': { 'Death Mote': 5 },
  'Life Wisp': { 'Life Mote': 5 },
  'Soul Wisp': { 'Soul Mote': 5 },
  'Fire Essence': { 'Fire Mote': 20 },
  'Earth Essence': { 'Earth Mote': 20 },
  'Air Essence': { 'Air Mote': 20 },
  'Water Essence': { 'Water Mote': 20 },
  'Death Essence': { 'Death Mote': 20 },
  'Life Essence': { 'Life Mote': 20 },
  'Soul Essence': { 'Soul Mote': 20 },
  'Fire Quintessence': { 'Fire Mote': 60 },
  'Earth Quintessence': { 'Earth Mote': 60 },
  'Air Quintessence': { 'Air Mote': 60 },
  'Water Quintessence': { 'Water Mote': 60 },
  'Death Quintessence': { 'Death Mote': 60 },
  'Life Quintessence': { 'Life Mote': 60 },
  'Soul Quintessence': { 'Soul Mote': 60 },

  Gunpowder: {
    Saltpeter: 0.2,
    Charcoal: 1,
  },

  'Ash Stain': { Charcoal: 1, 'Weak Solvent': 0.4 },
  'Maple Stain': { Oil: 0.4, 'Weak Solvent': 1 },
  'Oak Stain': { 'Potent Solvent': 1, Oil: 0.4 },

  'Stone Block': { Stone: 4 },
  'Stone Brick': { Stone: 16, 'Coarse Sandpaper': 1 },
  'Lodestone Brick': { Stone: 32, Lodestone: 6, 'Coarse Sandpaper': 3 },
  'Obsidian Voidstone': { Stone: 256, Lodestone: 50, 'Coarse Sandpaper': 25 },
}

export const defaultMaterialPrice = {
  'Iron Ore': 0.42,
  'Iron Ingot': 1.2,
  'Steel Ingot': 3.49,
  'Sand Flux': 0.08,
  'Starmetal Ore': 0.1,
  'Starmetal Ingot': 9.38,
  'Orichalcum Ore': 0.48,
  'Orichalcum Ingot': 24.99,
  Charcoal: 0.19,
  'Raw Hide': 0.26,
  Tannin: 0.03,
  'Coarse Leather': 0.48,
  'Rugged Leather': 1.99,
  'Thick Hide': 0.1,
  'Layered Leather': 5.5,
  'Iron Hide': 0.1,
  'Infused Leather': 14,
  Fiber: 0.21,
  Linen: 0.76,
  Crossweave: 0.04,
  Sateen: 2.29,
  'Silk Threads': 0.08,
  Silk: 7.98,
  'Wire Fiber': 0.25,
  'Infused Silk': 15,
  'Green Wood': 0.13,
  Timber: 0.48,
  'Coarse Sandpaper': 0.1,
  'Aged Wood': 0.1,
  Lumber: 1.2,
  Wyrdwood: 0.09,
  'Wyrdwood Planks': 3.65,
  Ironwood: 0.75,
  'Ironwood Planks': 30,
  'Earth Mote': 0.65,
  'Fire Mote': 0.75,
  'Air Mote': 1,
  'Water Mote': 1.19,
  'Life Mote': 0.7,
  'Death Mote': 0.77,
  'Soul Mote': 0.44,
  'Earth Wisp': 5,
  'Fire Wisp': 4.5,
  'Air Wisp': 4,
  'Water Wisp': 4,
  'Life Wisp': 2.74,
  'Death Wisp': 2,
  'Soul Wisp': 2,
  'Earth Essence': 20,
  'Fire Essence': 20,
  'Air Essence': 25,
  'Water Essence': 21.2,
  'Life Essence': 16.99,
  'Death Essence': 14.9,
  'Soul Essence': 25,
  Fur: 9.5,
  'Thick Fur': 20,
  'Infused Fur': 50,
  'Silver Ore': 0.15,
  'Silver Ingot': 0.4,
  'Gold Ore': 0.02,
  'Gold Ingot': 0.3,
  'Platinum Ore': 0.6,
  'Platinum Ingot': 0.97,
  Gunpowder: 0.01,
  Saltpeter: 0.25,
  'Fae Iron': 0.38,
  Oil: 1,
  'Void Steel': 19,
  Cinnabar: 115,
  Hyssop: 0.1,
  'Weak Solvent': 0.06,
  'Ash Stain': 0.01,
  'Maple Stain': 0.25,
  'Oak Stain': 0.04,
  'Potent Solvent': 0.04,
  Stone: 0.15,
  'Lodestone Brick': 1.9,
  'Stone Brick': 0.18,
  'Stone Block': 0.3,
  Lodestone: 0.15,
  'Obsidian Voidstone': 0,
}
