export const weaponsmithingRecipes = [
  {
    itemName: 'Sacred Demise',
    xp: '7,285',
    recipeID: '2hWarhammer_SacredDemiseT5',
    craftingFee: 449,
    recipeLevel: 196,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EmpoweredCounterbalanceT5',
    type4: 'Item',
    ingredient5: 'Tolvium',
    type5: 'Item',
    ingredient6: 'Scarhide',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Deceit of the Defiler',
    xp: '990',
    recipeID: '1hRapier_DeceitoftheDefilerT3',
    craftingFee: 75,
    recipeLevel: 83,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Voidmetal',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'The First of Many',
    xp: '990',
    recipeID: '1hLongsword_TheFirstOfManyT3',
    craftingFee: 75,
    recipeLevel: 75,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Voidmetal',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Common Honing Stone',
    xp: '90',
    recipeID: 'HoningStoneT3',
    craftingFee: 15,
    recipeLevel: 70,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Stone Brick',
    type1: 'Item',
    ingredient2: 'Death Wisp',
    type2: 'Item',
    ingredient3: 'Fire Wisp',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Weak Honing Stone',
    xp: '36',
    recipeID: 'HoningStoneT2',
    craftingFee: 5,
    recipeLevel: 20,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Stone Block',
    type1: 'Item',
    ingredient2: 'Death Mote',
    type2: 'Item',
    ingredient3: 'Fire Mote',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Amrine Temple Round Shield',
    xp: '660',
    recipeID: '2hRoundShieldCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'Vial Of Ectoplasmic Mutagen',
    type5: 'Item',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Defender of Darkness',
    xp: '1,440',
    recipeID: '2hWarhammer_DefenderofDarknessT3',
    craftingFee: 75,
    recipeLevel: 76,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Voidmetal',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Garden Keeper Longsword',
    xp: '3,720',
    recipeID: '1hLongswordCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sticky Vines',
    type4: 'Item',
    ingredient5: 'Putrid Bark',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Shipyard Sentinel Rapier',
    xp: '1,725',
    recipeID: '1hRapierCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: "Warrior's Breath",
    xp: '7,285',
    recipeID: '2hGreataxe_WarriorsBreathT5',
    craftingFee: 449,
    recipeLevel: 187,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EmpoweredCounterbalanceT5',
    type4: 'Item',
    ingredient5: 'Cinnabar',
    type5: 'Item',
    ingredient6: 'Smolderhide',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Pestilence',
    xp: '7,285',
    recipeID: '2hGreataxe_PestilenceT5',
    craftingFee: 449,
    recipeLevel: 197,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EmpoweredCounterbalanceT5',
    type4: 'Item',
    ingredient5: 'Tolvium',
    type5: 'Item',
    ingredient6: 'Scarhide',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Sapling Brand',
    xp: '396',
    recipeID: '1hLongsword_SaplingBrandT2',
    craftingFee: 25,
    recipeLevel: 25,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Coarse Leather',
    type2: 'Item',
    ingredient3: 'Timber',
    type3: 'Item',
    ingredient4: 'Silver Ingot',
    type4: 'Item',
    ingredient5: 'Fae Iron',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Obelisk Guard Longsword',
    xp: '660',
    recipeID: '1hLongswordCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SparklingBoneDustT1',
    type4: 'Item',
    ingredient5: 'MutagentAncientT1',
    type5: 'Item',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Tipping Point',
    xp: '1,440',
    recipeID: '2hGreataxe_TippingPointT3',
    craftingFee: 75,
    recipeLevel: 82,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Voidmetal',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Iron Round Shield',
    xp: '120',
    recipeID: 'Procedural_ShieldRoundT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 7,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Starmetal War Hammer',
    xp: '1,425',
    recipeID: 'Procedural_WarHammerT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Steel Longsword',
    xp: '330',
    recipeID: 'Procedural_LongswordT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Obelisk Guard Great Axe',
    xp: '870',
    recipeID: '2hGreataxeCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SparklingBoneDustT1',
    type4: 'Item',
    ingredient5: 'MutagentAncientT1',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Deepwatcher Rapier',
    xp: '1,725',
    recipeID: '1hRapierCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Tearsteal Rapier',
    xp: '2,625',
    recipeID: '1hRapier_TearstealRapierT4',
    craftingFee: 184,
    recipeLevel: 148,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'AzuriteChunkT1',
    type5: 'Item',
    ingredient6: 'ShifthideT1',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Timeripping Great Axe',
    xp: '3,750',
    recipeID: '2hGreataxe_TimerippingGreataxeT4',
    craftingFee: 184,
    recipeLevel: 142,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'BlessedCrucibleT1',
    type5: 'Item',
    ingredient6: 'BrightscaleHideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Garden Keeper Tower Shield',
    xp: '4,185',
    recipeID: '2hTowerShieldCraftedDungeon7T5',
    craftingFee: 748,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sticky Vines',
    type4: 'Item',
    ingredient5: 'Putrid Bark',
    type5: 'Item',
    qty1: 13,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Starmetal Round Shield',
    xp: '900',
    recipeID: 'Procedural_ShieldRoundT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: "Archmage's Steel Wand",
    xp: '2,625',
    recipeID: '1hRapier_ArchmagesSteelWandT4',
    craftingFee: 184,
    recipeLevel: 143,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'BlessedCrucibleT1',
    type5: 'Item',
    ingredient6: 'BrightscaleHideT1',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Hammer of Forgotten Dreams',
    xp: '3,750',
    recipeID: '2hWarhammer_HammerofForgottenDreamsT4',
    craftingFee: 75,
    recipeLevel: 136,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'BlessedCrucibleT1',
    type5: 'Item',
    ingredient6: 'BrightscaleHideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Tidal Reaver',
    xp: '990',
    recipeID: '1hLongsword_TidalReaverT3',
    craftingFee: 75,
    recipeLevel: 80,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Voidmetal',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Masterstroke',
    xp: '4,960',
    recipeID: '1hLongsword_MasterstrokeT5',
    craftingFee: 449,
    recipeLevel: 190,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EtchedHandguardT5',
    type4: 'Item',
    ingredient5: 'Tolvium',
    type5: 'Item',
    ingredient6: 'Scarhide',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Steel Rapier',
    xp: '330',
    recipeID: 'Procedural_RapierT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Starmetal Rapier',
    xp: '900',
    recipeID: 'Procedural_RapierT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Crystalline Crusher',
    xp: '1,440',
    recipeID: '2hWarhammer_CrystallineCrusherT3',
    craftingFee: 75,
    recipeLevel: 81,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Voidmetal',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Lazarus Watcher Round Shield',
    xp: '3,720',
    recipeID: '2hRoundShieldCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Obelisk Guard Kite Shield',
    xp: '690',
    recipeID: '2hKiteShieldCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SparklingBoneDustT1',
    type4: 'Item',
    ingredient5: 'MutagentAncientT1',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Orichalcum Round Shield',
    xp: '2,015',
    recipeID: 'Procedural_ShieldRoundT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Balance of Time',
    xp: '2,625',
    recipeID: '1hLongsword_BalanceOfTimeT3',
    craftingFee: 75,
    recipeLevel: 135,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'BlessedCrucibleT1',
    type5: 'Item',
    ingredient6: 'BrightscaleHideT1',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Iron Rapier',
    xp: '120',
    recipeID: 'Procedural_RapierT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 7,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Dowsing Blade',
    xp: '2,625',
    recipeID: '1hLongsword_DowsingBladeT4',
    craftingFee: 184,
    recipeLevel: 140,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'AzuriteChunkT1',
    type5: 'Item',
    ingredient6: 'ShifthideT1',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Steel Great Axe',
    xp: '540',
    recipeID: 'Procedural_2hGreatAxeT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Graiths Maul',
    xp: '7,285',
    recipeID: '2hWarhammer_GraithsMaulT5',
    craftingFee: 449,
    recipeLevel: 191,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EmpoweredCounterbalanceT5',
    type4: 'Item',
    ingredient5: 'Cinnabar',
    type5: 'Item',
    ingredient6: 'Smolderhide',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Iron Longsword',
    xp: '120',
    recipeID: 'Procedural_LongswordT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 7,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Iron Great Axe',
    xp: '204',
    recipeID: 'Procedural_2hGreatAxeT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Honorbound Rapier',
    xp: '4,960',
    recipeID: '1hRapier_HonorboundRapierT5',
    craftingFee: 449,
    recipeLevel: 198,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EtchedHandguardT5',
    type4: 'Item',
    ingredient5: 'Tolvium',
    type5: 'Item',
    ingredient6: 'Scarhide',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Shipyard Sentinal Tower Shield',
    xp: '1,950',
    recipeID: '2hTowerShieldCraftedDungeon5T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 12,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Starmetal Longsword',
    xp: '900',
    recipeID: 'Procedural_LongswordT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Amrine Temple War Hammer',
    xp: '870',
    recipeID: '2hWarhammerCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'Vial Of Ectoplasmic Mutagen',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Great Axe of the Colossal Breach',
    xp: '1,440',
    recipeID: '2hGreataxe_GreataxeoftheCollosalBreachT3',
    craftingFee: 75,
    recipeLevel: 77,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Voidmetal',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Amrine Temple Kite Shield',
    xp: '690',
    recipeID: '2hKiteShieldCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'Vial Of Ectoplasmic Mutagen',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Amrine Temple Rapier',
    xp: '660',
    recipeID: '1hRapierCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'Vial Of Ectoplasmic Mutagen',
    type5: 'Item',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Earth Battered Axe',
    xp: '576',
    recipeID: '2hGreataxe_EarthBatteredAxeT2',
    craftingFee: 25,
    recipeLevel: 27,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Coarse Leather',
    type2: 'Item',
    ingredient3: 'Timber',
    type3: 'Item',
    ingredient4: 'Silver Ingot',
    type4: 'Item',
    ingredient5: 'Fae Iron',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Renaissance',
    xp: '4,960',
    recipeID: '1hRapier_RenaissanceT5',
    craftingFee: 449,
    recipeLevel: 188,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EtchedHandguardT5',
    type4: 'Item',
    ingredient5: 'Cinnabar',
    type5: 'Item',
    ingredient6: 'Smolderhide',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Orichalcum Tower Shield',
    xp: '2,480',
    recipeID: 'Procedural_ShieldTowerT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Shipyard Sentinel Longsword',
    xp: '1,725',
    recipeID: '1hLongswordCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Orichalcum Rapier',
    xp: '2,015',
    recipeID: 'Procedural_RapierT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Powerful Honing Stone',
    xp: '465',
    recipeID: 'HoningStoneT5',
    craftingFee: 90,
    recipeLevel: 170,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Obsidian Voidstone',
    type1: 'Item',
    ingredient2: 'Death Quintessence',
    type2: 'Item',
    ingredient3: 'Fire Quintessence',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Lazarus Watcher Great Axe',
    xp: '4,805',
    recipeID: '2hGreataxeCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Amrine Temple Great Axe',
    xp: '870',
    recipeID: '2hGreataxeCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'Vial Of Ectoplasmic Mutagen',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Opus Blade',
    xp: '4,960',
    recipeID: '1hLongsword_OpusBladeT5',
    craftingFee: 449,
    recipeLevel: 185,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Asmodeum',
    type1: 'Item',
    ingredient2: 'Runic Leather',
    type2: 'Item',
    ingredient3: 'Glittering Ebony',
    type3: 'Item',
    ingredient4: 'EtchedHandguardT5',
    type4: 'Item',
    ingredient5: 'Cinnabar',
    type5: 'Item',
    ingredient6: 'Smolderhide',
    type6: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 1,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Starmetal Tower Shield',
    xp: '1,125',
    recipeID: 'Procedural_ShieldTowerT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Garden Keeper Round Shield',
    xp: '3,720',
    recipeID: '2hRoundShieldCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sticky Vines',
    type4: 'Item',
    ingredient5: 'Putrid Bark',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Twig of the Azoth Tree',
    xp: '396',
    recipeID: '1hRapier_TwigoftheAzothTreeT2',
    craftingFee: 25,
    recipeLevel: 28,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Coarse Leather',
    type2: 'Item',
    ingredient3: 'Timber',
    type3: 'Item',
    ingredient4: 'Silver Ingot',
    type4: 'Item',
    ingredient5: 'Fae Iron',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Deepwatcher Round Shield',
    xp: '1,725',
    recipeID: '2hRoundShieldCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Lazarus Watcher War Hammer',
    xp: '4,805',
    recipeID: '2hWarhammerCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Deepwatcher Great Axe',
    xp: '2,250',
    recipeID: '2hGreataxeCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Shipyard Sentinel Round Shield',
    xp: '1,725',
    recipeID: '2hRoundShieldCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Steel Round Shield',
    xp: '330',
    recipeID: 'Procedural_ShieldRoundT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Orichalcum Longsword',
    xp: '2,015',
    recipeID: 'Procedural_LongswordT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Obelisk Guard Rapier',
    xp: '660',
    recipeID: '1hRapierCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SparklingBoneDustT1',
    type4: 'Item',
    ingredient5: 'MutagentAncientT1',
    type5: 'Item',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Garden Keeper Kite Shield',
    xp: '3,875',
    recipeID: '2hKiteShieldCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sticky Vines',
    type4: 'Item',
    ingredient5: 'Putrid Bark',
    type5: 'Item',
    qty1: 11,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Orichalcum Kite Shield',
    xp: '2,170',
    recipeID: 'Procedural_ShieldKiteT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 11,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Shipyard Sentinel Great Axe',
    xp: '2,250',
    recipeID: '2hGreataxeCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Iron War Hammer',
    xp: '204',
    recipeID: 'Procedural_WarHammerT2',
    craftingFee: 25,
    recipeLevel: 0,
    baseGearScore: 200,
    baseTier: 2,
    ingredient1: 'Iron Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 12,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: "Hulking Berserker's Battleaxe",
    xp: '3,750',
    recipeID: '2hGreataxe_HulkingBerserkersBattleaxeT4',
    craftingFee: 184,
    recipeLevel: 147,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'AzuriteChunkT1',
    type5: 'Item',
    ingredient6: 'ShifthideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Amrine Temple Longsword',
    xp: '660',
    recipeID: '1hLongswordCraftedDungeon1T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Coagulated Blood',
    type4: 'Item',
    ingredient5: 'Vial Of Ectoplasmic Mutagen',
    type5: 'Item',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Steel Kite Shield',
    xp: '360',
    recipeID: 'Procedural_ShieldKiteT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Garden Keeper Rapier',
    xp: '3,720',
    recipeID: '1hRapierCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sticky Vines',
    type4: 'Item',
    ingredient5: 'Putrid Bark',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Lazarus Watcher Kite Shield',
    xp: '3,875',
    recipeID: '2hKiteShieldCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 11,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Shattered Hope',
    xp: '3,750',
    recipeID: '2hWarhammer_ShatteredHopeT4',
    craftingFee: 184,
    recipeLevel: 141,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Starmetal Ingot',
    type1: 'Item',
    ingredient2: 'Layered Leather',
    type2: 'Item',
    ingredient3: 'Wyrdwood Planks',
    type3: 'Item',
    ingredient4: 'Platinum Ingot',
    type4: 'Item',
    ingredient5: 'AzuriteChunkT1',
    type5: 'Item',
    ingredient6: 'ShifthideT1',
    type6: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 2,
    qty7: 0,
    numberOfIngredients: 6,
  },
  {
    itemName: 'Garden Keeper War Hammer',
    xp: '4,805',
    recipeID: '2hWarhammerCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sticky Vines',
    type4: 'Item',
    ingredient5: 'Putrid Bark',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Steel War Hammer',
    xp: '540',
    recipeID: 'Procedural_WarHammerT3',
    craftingFee: 75,
    recipeLevel: 50,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Lazarus Watcher Rapier',
    xp: '3,720',
    recipeID: '1hRapierCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Obelisk Guard War Hammer',
    xp: '870',
    recipeID: '2hWarhammerCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SparklingBoneDustT1',
    type4: 'Item',
    ingredient5: 'MutagentAncientT1',
    type5: 'Item',
    qty1: 13,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Wood Longsword',
    xp: '',
    recipeID: '1hSwordT1',
    craftingFee: 0,
    recipeLevel: 0,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'WoodT1',
    type1: 'Item',
    ingredient2: 'RawhideT1',
    type2: 'Item',
    qty1: 1,
    qty2: 1,
    qty3: 0,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 2,
  },
  {
    itemName: 'Balanced Blade',
    xp: '990',
    recipeID: '1hRapier_BalancedBladeT3',
    craftingFee: 75,
    recipeLevel: 78,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Steel Ingot',
    type1: 'Item',
    ingredient2: 'Rugged Leather',
    type2: 'Item',
    ingredient3: 'Lumber',
    type3: 'Item',
    ingredient4: 'Gold Ingot',
    type4: 'Item',
    ingredient5: 'Voidmetal',
    type5: 'Item',
    qty1: 14,
    qty2: 8,
    qty3: 3,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Earthen Smasher',
    xp: '576',
    recipeID: '2hWarhammer_EarthenSmasherT2',
    craftingFee: 25,
    recipeLevel: 26,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Iron Ingot',
    type1: 'Item',
    ingredient2: 'Coarse Leather',
    type2: 'Item',
    ingredient3: 'Timber',
    type3: 'Item',
    ingredient4: 'Silver Ingot',
    type4: 'Item',
    ingredient5: 'Fae Iron',
    type5: 'Item',
    qty1: 20,
    qty2: 15,
    qty3: 5,
    qty4: 4,
    qty5: 4,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Starmetal Great axe',
    xp: '1,425',
    recipeID: 'Procedural_2hGreatAxeT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Deepwatcher Tower Shield',
    xp: '1,950',
    recipeID: '2hTowerShieldCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 12,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Deepwatcher Kite Shield',
    xp: '1,800',
    recipeID: '2hKiteShieldCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Orichalcum War Hammer',
    xp: '3,100',
    recipeID: 'Procedural_WarHammerT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Shipyard Sentinel War Hammer',
    xp: '2,250',
    recipeID: '2hWarhammerCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Strong Honing Stone',
    xp: '225',
    recipeID: 'HoningStoneT4',
    craftingFee: 37,
    recipeLevel: 120,
    baseGearScore: 0,
    baseTier: 0,
    ingredient1: 'Lodestone Brick',
    type1: 'Item',
    ingredient2: 'Death Essence',
    type2: 'Item',
    ingredient3: 'Fire Essence',
    qty1: 1,
    qty2: 1,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Garden Keeper Great Axe',
    xp: '4,805',
    recipeID: '2hGreataxeCraftedDungeon7T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Sticky Vines',
    type4: 'Item',
    ingredient5: 'Putrid Bark',
    type5: 'Item',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Orichalcum Great Axe',
    xp: '3,100',
    recipeID: 'Procedural_2hGreatAxeT5',
    craftingFee: 449,
    recipeLevel: 150,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 15,
    qty2: 3,
    qty3: 2,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Lazarus Watcher Longsword',
    xp: '3,720',
    recipeID: '1hLongswordCraftedDungeon6T5',
    craftingFee: 449,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    ingredient6: 'Jade Collar',
    type6: 'Item',
    ingredient7: 'Jade Talisman',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Starmetal Kite Shield',
    xp: '975',
    recipeID: 'Procedural_ShieldKiteT4',
    craftingFee: 184,
    recipeLevel: 100,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 0,
    qty5: 0,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 3,
  },
  {
    itemName: 'Deepwatcher Longsword',
    xp: '1,725',
    recipeID: '1hLongswordCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 9,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Lazarus Watcher Tower Shield',
    xp: '4,185',
    recipeID: '2hTowerShieldCraftedDungeon6T5',
    craftingFee: 748,
    recipeLevel: 160,
    baseGearScore: 500,
    baseTier: 5,
    ingredient1: 'Orichalcum Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SpectralDustT1',
    type4: 'Item',
    ingredient5: 'MetallicBoneweaveT1',
    type5: 'Item',
    qty1: 13,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Shipyard Sentinel Kite Shield',
    xp: '1,800',
    recipeID: '2hKiteShieldCraftedDungeon5T4',
    craftingFee: 449,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'Jade Collar',
    type4: 'Item',
    ingredient5: 'Jade Talisman',
    type5: 'Item',
    qty1: 10,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Deepwatcher War Hammer',
    xp: '2,250',
    recipeID: '2hWarhammerCraftedDungeon4T4',
    craftingFee: 184,
    recipeLevel: 110,
    baseGearScore: 400,
    baseTier: 4,
    ingredient1: 'Starmetal Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'CorruptedTalismanT1',
    type4: 'Item',
    ingredient5: 'CorruptedTreatiseT1',
    type5: 'Item',
    qty1: 14,
    qty2: 3,
    qty3: 2,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
  {
    itemName: 'Obelisk Guard Round Shield',
    xp: '660',
    recipeID: '2hRoundShieldCraftedDungeon2T3',
    craftingFee: 75,
    recipeLevel: 60,
    baseGearScore: 300,
    baseTier: 3,
    ingredient1: 'Steel Ingot',
    type1: 'Category_Only',
    ingredient2: 'Timber',
    type2: 'Category_Only',
    ingredient3: 'Coarse Leather',
    type3: 'Category_Only',
    ingredient4: 'SparklingBoneDustT1',
    type4: 'Item',
    ingredient5: 'MutagentAncientT1',
    type5: 'Item',
    qty1: 8,
    qty2: 2,
    qty3: 1,
    qty4: 10,
    qty5: 1,
    qty6: 0,
    qty7: 0,
    numberOfIngredients: 5,
  },
]
